
# example config file for vpv/utils/data_loader.py

# Any variable that will be repeated within the config can be defined as an anchor using '&'
#target: &/mnt/bit_nfs/neil/impc_e18.5/jax/test_run_210121/target/Harwell_E18.5_avg.nrrd

view_template:
  ori: 'sagittal'
  top:
    color: red
    opacity: 1.0
  bottom:
    path: '/mnt/bit_nfs/neil/impc_e18.5/jax/test_run_210121/target/Harwell_E18.5_avg.nrrd'
    color: cyan
    opacity: 1.0



### Define up to 6 views. Override any artibutes from the template
views:
  - top:
      path: '**/*reg*/rigid/**/*.nrrd'
  - top:
      path: '**/*reg*/affine/**/*.nrrd'
  - top:
      path: '**/*reg*/def*64/**/*.nrrd'
  - top:
      path: '**/*reg*/def*32/**/*.nrrd'
  - top:
      path: '**/*reg*/def*16/**/*.nrrd'
  - top:
      path: '**/*reg*/def*8/**/*.nrrd'
