# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_annotations.ui'
#
# Created: Wed Oct  5 11:00:45 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Annotations(object):
    def setupUi(self, Annotations):
        Annotations.setObjectName(_fromUtf8("Annotations"))
        Annotations.resize(573, 776)
        Annotations.setMinimumSize(QtCore.QSize(0, 40))
        self.verticalLayout_17 = QtGui.QVBoxLayout(Annotations)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBoxAnnotationsVolumes = QtGui.QComboBox(Annotations)
        self.comboBoxAnnotationsVolumes.setObjectName(_fromUtf8("comboBoxAnnotationsVolumes"))
        self.verticalLayout.addWidget(self.comboBoxAnnotationsVolumes)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_34 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_20.addWidget(self.label_34)
        self.labelXPos = QtGui.QLabel(Annotations)
        self.labelXPos.setObjectName(_fromUtf8("labelXPos"))
        self.horizontalLayout_20.addWidget(self.labelXPos)
        self.label_35 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_20.addWidget(self.label_35)
        self.labelYPos = QtGui.QLabel(Annotations)
        self.labelYPos.setObjectName(_fromUtf8("labelYPos"))
        self.horizontalLayout_20.addWidget(self.labelYPos)
        self.label_36 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_20.addWidget(self.label_36)
        self.labelZPos = QtGui.QLabel(Annotations)
        self.labelZPos.setObjectName(_fromUtf8("labelZPos"))
        self.horizontalLayout_20.addWidget(self.labelZPos)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_3 = QtGui.QFrame(Annotations)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBoxAnnotationType = QtGui.QGroupBox(Annotations)
        self.groupBoxAnnotationType.setObjectName(_fromUtf8("groupBoxAnnotationType"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxAnnotationType)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButtonUseMp = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonUseMp.setChecked(True)
        self.radioButtonUseMp.setObjectName(_fromUtf8("radioButtonUseMp"))
        self.gridLayout_3.addWidget(self.radioButtonUseMp, 1, 0, 1, 1)
        self.radioButtonUseMaPato = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonUseMaPato.setObjectName(_fromUtf8("radioButtonUseMaPato"))
        self.gridLayout_3.addWidget(self.radioButtonUseMaPato, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBoxAnnotationType)
        self.line = QtGui.QFrame(Annotations)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.groupBoxStage = QtGui.QGroupBox(Annotations)
        self.groupBoxStage.setObjectName(_fromUtf8("groupBoxStage"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxStage)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.radioButtonE185 = QtGui.QRadioButton(self.groupBoxStage)
        self.radioButtonE185.setChecked(True)
        self.radioButtonE185.setObjectName(_fromUtf8("radioButtonE185"))
        self.gridLayout_4.addWidget(self.radioButtonE185, 2, 0, 1, 1)
        self.radioButtonE125 = QtGui.QRadioButton(self.groupBoxStage)
        self.radioButtonE125.setObjectName(_fromUtf8("radioButtonE125"))
        self.gridLayout_4.addWidget(self.radioButtonE125, 0, 0, 1, 1)
        self.radioButtonE145 = QtGui.QRadioButton(self.groupBoxStage)
        self.radioButtonE145.setObjectName(_fromUtf8("radioButtonE145"))
        self.gridLayout_4.addWidget(self.radioButtonE145, 1, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBoxStage)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtGui.QFrame(Annotations)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.maPatoWidget = QtGui.QWidget(Annotations)
        self.maPatoWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.maPatoWidget.setObjectName(_fromUtf8("maPatoWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.maPatoWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_32 = QtGui.QLabel(self.maPatoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_2.addWidget(self.label_32)
        self.comboBoxMaTerms = QtGui.QComboBox(self.maPatoWidget)
        self.comboBoxMaTerms.setObjectName(_fromUtf8("comboBoxMaTerms"))
        self.horizontalLayout_2.addWidget(self.comboBoxMaTerms)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_33 = QtGui.QLabel(self.maPatoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_3.addWidget(self.label_33)
        self.comboBoxPatoTerms = QtGui.QComboBox(self.maPatoWidget)
        self.comboBoxPatoTerms.setObjectName(_fromUtf8("comboBoxPatoTerms"))
        self.horizontalLayout_3.addWidget(self.comboBoxPatoTerms)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.maPatoWidget)
        self.mpWidget = QtGui.QWidget(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpWidget.sizePolicy().hasHeightForWidth())
        self.mpWidget.setSizePolicy(sizePolicy)
        self.mpWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.mpWidget.setObjectName(_fromUtf8("mpWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.mpWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.mpWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxMpTerms = QtGui.QComboBox(self.mpWidget)
        self.comboBoxMpTerms.setObjectName(_fromUtf8("comboBoxMpTerms"))
        self.horizontalLayout.addWidget(self.comboBoxMpTerms)
        self.verticalLayout.addWidget(self.mpWidget)
        self.pushButtonAddAnnotation = QtGui.QPushButton(Annotations)
        self.pushButtonAddAnnotation.setObjectName(_fromUtf8("pushButtonAddAnnotation"))
        self.verticalLayout.addWidget(self.pushButtonAddAnnotation)
        self.label_31 = QtGui.QLabel(Annotations)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout.addWidget(self.label_31)
        self.textEditFreetext = QtGui.QTextEdit(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditFreetext.sizePolicy().hasHeightForWidth())
        self.textEditFreetext.setSizePolicy(sizePolicy)
        self.textEditFreetext.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEditFreetext.setObjectName(_fromUtf8("textEditFreetext"))
        self.verticalLayout.addWidget(self.textEditFreetext)
        self.labelAvailableAnnotations = QtGui.QLabel(Annotations)
        self.labelAvailableAnnotations.setText(_fromUtf8(""))
        self.labelAvailableAnnotations.setObjectName(_fromUtf8("labelAvailableAnnotations"))
        self.verticalLayout.addWidget(self.labelAvailableAnnotations)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinBoxAnnotationCircleSize = QtGui.QSpinBox(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxAnnotationCircleSize.sizePolicy().hasHeightForWidth())
        self.spinBoxAnnotationCircleSize.setSizePolicy(sizePolicy)
        self.spinBoxAnnotationCircleSize.setProperty("value", 10)
        self.spinBoxAnnotationCircleSize.setObjectName(_fromUtf8("spinBoxAnnotationCircleSize"))
        self.horizontalLayout_6.addWidget(self.spinBoxAnnotationCircleSize)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.tableViewAvailableAnnotations = QtGui.QTableView(Annotations)
        self.tableViewAvailableAnnotations.setObjectName(_fromUtf8("tableViewAvailableAnnotations"))
        self.verticalLayout.addWidget(self.tableViewAvailableAnnotations)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonSaveAnnotations = QtGui.QPushButton(Annotations)
        self.pushButtonSaveAnnotations.setObjectName(_fromUtf8("pushButtonSaveAnnotations"))
        self.horizontalLayout_5.addWidget(self.pushButtonSaveAnnotations)
        self.pushButtonRemoveAnnotation = QtGui.QPushButton(Annotations)
        self.pushButtonRemoveAnnotation.setObjectName(_fromUtf8("pushButtonRemoveAnnotation"))
        self.horizontalLayout_5.addWidget(self.pushButtonRemoveAnnotation)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addLayout(self.verticalLayout)

        self.retranslateUi(Annotations)
        QtCore.QMetaObject.connectSlotsByName(Annotations)

    def retranslateUi(self, Annotations):
        Annotations.setWindowTitle(_translate("Annotations", "Form", None))
        self.label_34.setText(_translate("Annotations", "X: ", None))
        self.labelXPos.setText(_translate("Annotations", "0", None))
        self.label_35.setText(_translate("Annotations", "Y:", None))
        self.labelYPos.setText(_translate("Annotations", "0", None))
        self.label_36.setText(_translate("Annotations", "Z:", None))
        self.labelZPos.setText(_translate("Annotations", "0", None))
        self.radioButtonUseMp.setText(_translate("Annotations", "Use MP", None))
        self.radioButtonUseMaPato.setText(_translate("Annotations", "Use EMAP/pato", None))
        self.radioButtonE185.setText(_translate("Annotations", "E18.5 terms", None))
        self.radioButtonE125.setText(_translate("Annotations", "E12.5 terms", None))
        self.radioButtonE145.setText(_translate("Annotations", "E14.5/E15.5 terms", None))
        self.label_32.setText(_translate("Annotations", "EMAP terms", None))
        self.label_33.setText(_translate("Annotations", "Pato terms", None))
        self.label.setText(_translate("Annotations", "MP terms", None))
        self.pushButtonAddAnnotation.setText(_translate("Annotations", "Add annotation", None))
        self.label_31.setText(_translate("Annotations", "Free text comments", None))
        self.label_2.setText(_translate("Annotations", "Annotation radius", None))
        self.pushButtonSaveAnnotations.setText(_translate("Annotations", "Save annotations", None))
        self.pushButtonRemoveAnnotation.setText(_translate("Annotations", "Remove annotation", None))

