# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_annotations.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Annotations(object):
    def setupUi(self, Annotations):
        Annotations.setObjectName(_fromUtf8("Annotations"))
        Annotations.resize(576, 802)
        Annotations.setMinimumSize(QtCore.QSize(0, 40))
        self.verticalLayout_17 = QtGui.QVBoxLayout(Annotations)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBoxAnnotationsVolumes = QtGui.QComboBox(Annotations)
        self.comboBoxAnnotationsVolumes.setObjectName(_fromUtf8("comboBoxAnnotationsVolumes"))
        self.verticalLayout.addWidget(self.comboBoxAnnotationsVolumes)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_34 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_20.addWidget(self.label_34)
        self.labelXPos = QtGui.QLabel(Annotations)
        self.labelXPos.setObjectName(_fromUtf8("labelXPos"))
        self.horizontalLayout_20.addWidget(self.labelXPos)
        self.label_35 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_20.addWidget(self.label_35)
        self.labelYPos = QtGui.QLabel(Annotations)
        self.labelYPos.setObjectName(_fromUtf8("labelYPos"))
        self.horizontalLayout_20.addWidget(self.labelYPos)
        self.label_36 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_20.addWidget(self.label_36)
        self.labelZPos = QtGui.QLabel(Annotations)
        self.labelZPos.setObjectName(_fromUtf8("labelZPos"))
        self.horizontalLayout_20.addWidget(self.labelZPos)
        self.groupBoxAnnotationType = QtGui.QGroupBox(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAnnotationType.sizePolicy().hasHeightForWidth())
        self.groupBoxAnnotationType.setSizePolicy(sizePolicy)
        self.groupBoxAnnotationType.setObjectName(_fromUtf8("groupBoxAnnotationType"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBoxAnnotationType)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButtonE145 = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonE145.setCheckable(False)
        self.radioButtonE145.setObjectName(_fromUtf8("radioButtonE145"))
        self.horizontalLayout_2.addWidget(self.radioButtonE145)
        self.radioButtonE185 = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonE185.setCheckable(False)
        self.radioButtonE185.setChecked(False)
        self.radioButtonE185.setObjectName(_fromUtf8("radioButtonE185"))
        self.horizontalLayout_2.addWidget(self.radioButtonE185)
        self.radioButtonE125 = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonE125.setCheckable(False)
        self.radioButtonE125.setObjectName(_fromUtf8("radioButtonE125"))
        self.horizontalLayout_2.addWidget(self.radioButtonE125)
        self.radioButtonE155 = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonE155.setChecked(True)
        self.radioButtonE155.setObjectName(_fromUtf8("radioButtonE155"))
        self.horizontalLayout_2.addWidget(self.radioButtonE155)
        self.radioButtonE95 = QtGui.QRadioButton(self.groupBoxAnnotationType)
        self.radioButtonE95.setCheckable(False)
        self.radioButtonE95.setObjectName(_fromUtf8("radioButtonE95"))
        self.horizontalLayout_2.addWidget(self.radioButtonE95)
        self.horizontalLayout_20.addWidget(self.groupBoxAnnotationType)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_3 = QtGui.QFrame(Annotations)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line = QtGui.QFrame(Annotations)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.treeWidgetAvailableTerms = QtGui.QTreeWidget(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidgetAvailableTerms.sizePolicy().hasHeightForWidth())
        self.treeWidgetAvailableTerms.setSizePolicy(sizePolicy)
        self.treeWidgetAvailableTerms.setMinimumSize(QtCore.QSize(0, 300))
        self.treeWidgetAvailableTerms.setObjectName(_fromUtf8("treeWidgetAvailableTerms"))
        self.treeWidgetAvailableTerms.headerItem().setText(0, _fromUtf8("1"))
        self.horizontalLayout_4.addWidget(self.treeWidgetAvailableTerms)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtGui.QFrame(Annotations)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.pushButtonAddAnnotation = QtGui.QPushButton(Annotations)
        self.pushButtonAddAnnotation.setObjectName(_fromUtf8("pushButtonAddAnnotation"))
        self.verticalLayout.addWidget(self.pushButtonAddAnnotation)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinBoxAnnotationCircleSize = QtGui.QSpinBox(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxAnnotationCircleSize.sizePolicy().hasHeightForWidth())
        self.spinBoxAnnotationCircleSize.setSizePolicy(sizePolicy)
        self.spinBoxAnnotationCircleSize.setProperty("value", 10)
        self.spinBoxAnnotationCircleSize.setObjectName(_fromUtf8("spinBoxAnnotationCircleSize"))
        self.horizontalLayout_6.addWidget(self.spinBoxAnnotationCircleSize)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.tableViewAvailableAnnotations = QtGui.QTableView(Annotations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewAvailableAnnotations.sizePolicy().hasHeightForWidth())
        self.tableViewAvailableAnnotations.setSizePolicy(sizePolicy)
        self.tableViewAvailableAnnotations.setMinimumSize(QtCore.QSize(0, 0))
        self.tableViewAvailableAnnotations.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tableViewAvailableAnnotations.setObjectName(_fromUtf8("tableViewAvailableAnnotations"))
        self.verticalLayout.addWidget(self.tableViewAvailableAnnotations)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonSaveAnnotations = QtGui.QPushButton(Annotations)
        self.pushButtonSaveAnnotations.setObjectName(_fromUtf8("pushButtonSaveAnnotations"))
        self.horizontalLayout_5.addWidget(self.pushButtonSaveAnnotations)
        self.pushButtonRemoveAnnotation = QtGui.QPushButton(Annotations)
        self.pushButtonRemoveAnnotation.setObjectName(_fromUtf8("pushButtonRemoveAnnotation"))
        self.horizontalLayout_5.addWidget(self.pushButtonRemoveAnnotation)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addLayout(self.verticalLayout)

        self.retranslateUi(Annotations)
        QtCore.QMetaObject.connectSlotsByName(Annotations)

    def retranslateUi(self, Annotations):
        Annotations.setWindowTitle(_translate("Annotations", "Form", None))
        self.label_34.setText(_translate("Annotations", "X: ", None))
        self.labelXPos.setText(_translate("Annotations", "0", None))
        self.label_35.setText(_translate("Annotations", "Y:", None))
        self.labelYPos.setText(_translate("Annotations", "0", None))
        self.label_36.setText(_translate("Annotations", "Z:", None))
        self.labelZPos.setText(_translate("Annotations", "0", None))
        self.radioButtonE145.setText(_translate("Annotations", "E14.5", None))
        self.radioButtonE185.setText(_translate("Annotations", "E18.5", None))
        self.radioButtonE125.setText(_translate("Annotations", "E12.5", None))
        self.radioButtonE155.setText(_translate("Annotations", "E15.5", None))
        self.radioButtonE95.setText(_translate("Annotations", "E9.5", None))
        self.pushButtonAddAnnotation.setText(_translate("Annotations", "Add annotation", None))
        self.label_2.setText(_translate("Annotations", "Circle radius", None))
        self.pushButtonSaveAnnotations.setText(_translate("Annotations", "Save annotations", None))
        self.pushButtonRemoveAnnotation.setText(_translate("Annotations", "Remove annotation", None))

