# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_datatab.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_data(object):
    def setupUi(self, data):
        data.setObjectName(_fromUtf8("data"))
        data.resize(761, 839)
        self.verticalLayout = QtGui.QVBoxLayout(data)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutVolume = QtGui.QVBoxLayout()
        self.layoutVolume.setObjectName(_fromUtf8("layoutVolume"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_13 = QtGui.QLabel(data)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_6.addWidget(self.label_13)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkBoxLeftView = QtGui.QCheckBox(data)
        self.checkBoxLeftView.setText(_fromUtf8(""))
        self.checkBoxLeftView.setChecked(True)
        self.checkBoxLeftView.setObjectName(_fromUtf8("checkBoxLeftView"))
        self.horizontalLayout_8.addWidget(self.checkBoxLeftView)
        self.checkBoxCentralView = QtGui.QCheckBox(data)
        self.checkBoxCentralView.setText(_fromUtf8(""))
        self.checkBoxCentralView.setChecked(True)
        self.checkBoxCentralView.setObjectName(_fromUtf8("checkBoxCentralView"))
        self.horizontalLayout_8.addWidget(self.checkBoxCentralView)
        self.checkBoxRightView = QtGui.QCheckBox(data)
        self.checkBoxRightView.setText(_fromUtf8(""))
        self.checkBoxRightView.setChecked(True)
        self.checkBoxRightView.setObjectName(_fromUtf8("checkBoxRightView"))
        self.horizontalLayout_8.addWidget(self.checkBoxRightView)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.line_6 = QtGui.QFrame(data)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_6.addWidget(self.line_6)
        self.label = QtGui.QLabel(data)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayoutExtraButtons = QtGui.QHBoxLayout()
        self.horizontalLayoutExtraButtons.setObjectName(_fromUtf8("horizontalLayoutExtraButtons"))
        self.pushButtonManagerRed = QtGui.QPushButton(data)
        self.pushButtonManagerRed.setText(_fromUtf8(""))
        self.pushButtonManagerRed.setObjectName(_fromUtf8("pushButtonManagerRed"))
        self.horizontalLayoutExtraButtons.addWidget(self.pushButtonManagerRed)
        self.pushButtonManagerBlue = QtGui.QPushButton(data)
        self.pushButtonManagerBlue.setText(_fromUtf8(""))
        self.pushButtonManagerBlue.setObjectName(_fromUtf8("pushButtonManagerBlue"))
        self.horizontalLayoutExtraButtons.addWidget(self.pushButtonManagerBlue)
        self.pushButtonManagerGreen = QtGui.QPushButton(data)
        self.pushButtonManagerGreen.setText(_fromUtf8(""))
        self.pushButtonManagerGreen.setObjectName(_fromUtf8("pushButtonManagerGreen"))
        self.horizontalLayoutExtraButtons.addWidget(self.pushButtonManagerGreen)
        self.verticalLayout_6.addLayout(self.horizontalLayoutExtraButtons)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonManagerOrange = QtGui.QPushButton(data)
        self.pushButtonManagerOrange.setText(_fromUtf8(""))
        self.pushButtonManagerOrange.setObjectName(_fromUtf8("pushButtonManagerOrange"))
        self.horizontalLayout_9.addWidget(self.pushButtonManagerOrange)
        self.pushButtonManagerGrey = QtGui.QPushButton(data)
        self.pushButtonManagerGrey.setText(_fromUtf8(""))
        self.pushButtonManagerGrey.setObjectName(_fromUtf8("pushButtonManagerGrey"))
        self.horizontalLayout_9.addWidget(self.pushButtonManagerGrey)
        self.pushButtonManagerCyan = QtGui.QPushButton(data)
        self.pushButtonManagerCyan.setText(_fromUtf8(""))
        self.pushButtonManagerCyan.setObjectName(_fromUtf8("pushButtonManagerCyan"))
        self.horizontalLayout_9.addWidget(self.pushButtonManagerCyan)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.line_7 = QtGui.QFrame(data)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkBoxInterpolate = QtGui.QCheckBox(data)
        self.checkBoxInterpolate.setObjectName(_fromUtf8("checkBoxInterpolate"))
        self.verticalLayout_7.addWidget(self.checkBoxInterpolate)
        self.checkBoxLinkViews = QtGui.QCheckBox(data)
        self.checkBoxLinkViews.setChecked(True)
        self.checkBoxLinkViews.setObjectName(_fromUtf8("checkBoxLinkViews"))
        self.verticalLayout_7.addWidget(self.checkBoxLinkViews)
        self.checkBox6Views = QtGui.QCheckBox(data)
        self.checkBox6Views.setObjectName(_fromUtf8("checkBox6Views"))
        self.verticalLayout_7.addWidget(self.checkBox6Views)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.line_8 = QtGui.QFrame(data)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout.addWidget(self.line_8)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_2 = QtGui.QLabel(data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_9.addWidget(self.label_2)
        self.comboBoxOrientation = QtGui.QComboBox(data)
        self.comboBoxOrientation.setObjectName(_fromUtf8("comboBoxOrientation"))
        self.comboBoxOrientation.addItem(_fromUtf8(""))
        self.comboBoxOrientation.addItem(_fromUtf8(""))
        self.comboBoxOrientation.addItem(_fromUtf8(""))
        self.comboBoxOrientation.addItem(_fromUtf8(""))
        self.verticalLayout_9.addWidget(self.comboBoxOrientation)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBoxFlipXY = QtGui.QCheckBox(data)
        self.checkBoxFlipXY.setObjectName(_fromUtf8("checkBoxFlipXY"))
        self.horizontalLayout_4.addWidget(self.checkBoxFlipXY)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonScaleBarColor = QtGui.QPushButton(data)
        self.pushButtonScaleBarColor.setObjectName(_fromUtf8("pushButtonScaleBarColor"))
        self.horizontalLayout_5.addWidget(self.pushButtonScaleBarColor)
        self.pushButtonScreenShot = QtGui.QPushButton(data)
        self.pushButtonScreenShot.setStyleSheet(_fromUtf8("border: none"))
        self.pushButtonScreenShot.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Camera_font_awesome.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonScreenShot.setIcon(icon)
        self.pushButtonScreenShot.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonScreenShot.setObjectName(_fromUtf8("pushButtonScreenShot"))
        self.horizontalLayout_5.addWidget(self.pushButtonScreenShot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.layoutVolume.addLayout(self.horizontalLayout)
        self.line_5 = QtGui.QFrame(data)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.layoutVolume.addWidget(self.line_5)
        self.labelVolume = QtGui.QLabel(data)
        self.labelVolume.setStyleSheet(_fromUtf8("background-color:rgb(102, 95, 95);\n"
"padding: 3px;\n"
"color: rgb(223, 223, 223);"))
        self.labelVolume.setObjectName(_fromUtf8("labelVolume"))
        self.layoutVolume.addWidget(self.labelVolume)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBoxVolume = QtGui.QComboBox(data)
        self.comboBoxVolume.setObjectName(_fromUtf8("comboBoxVolume"))
        self.horizontalLayout_2.addWidget(self.comboBoxVolume)
        self.pushButtonEditVolName = QtGui.QPushButton(data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEditVolName.sizePolicy().hasHeightForWidth())
        self.pushButtonEditVolName.setSizePolicy(sizePolicy)
        self.pushButtonEditVolName.setStyleSheet(_fromUtf8("border:none"))
        self.pushButtonEditVolName.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEditVolName.setIcon(icon1)
        self.pushButtonEditVolName.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonEditVolName.setObjectName(_fromUtf8("pushButtonEditVolName"))
        self.horizontalLayout_2.addWidget(self.pushButtonEditVolName)
        self.layoutVolume.addLayout(self.horizontalLayout_2)
        self.horizontalLayoutVol1Levels = QtGui.QHBoxLayout()
        self.horizontalLayoutVol1Levels.setObjectName(_fromUtf8("horizontalLayoutVol1Levels"))
        self.comboBoxVolumeLut = QtGui.QComboBox(data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxVolumeLut.sizePolicy().hasHeightForWidth())
        self.comboBoxVolumeLut.setSizePolicy(sizePolicy)
        self.comboBoxVolumeLut.setObjectName(_fromUtf8("comboBoxVolumeLut"))
        self.horizontalLayoutVol1Levels.addWidget(self.comboBoxVolumeLut)
        self.layoutVolume.addLayout(self.horizontalLayoutVol1Levels)
        self.verticalLayout.addLayout(self.layoutVolume)
        self.line = QtGui.QFrame(data)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.vol2Widget_layout = QtGui.QVBoxLayout()
        self.vol2Widget_layout.setObjectName(_fromUtf8("vol2Widget_layout"))
        self.volume2Label_layout = QtGui.QHBoxLayout()
        self.volume2Label_layout.setObjectName(_fromUtf8("volume2Label_layout"))
        self.checkBoxShowVol2Controls = QtGui.QCheckBox(data)
        self.checkBoxShowVol2Controls.setMaximumSize(QtCore.QSize(20, 16777215))
        self.checkBoxShowVol2Controls.setText(_fromUtf8(""))
        self.checkBoxShowVol2Controls.setObjectName(_fromUtf8("checkBoxShowVol2Controls"))
        self.volume2Label_layout.addWidget(self.checkBoxShowVol2Controls)
        self.label_14 = QtGui.QLabel(data)
        self.label_14.setStyleSheet(_fromUtf8("background-color:rgb(102, 95, 95);\n"
"padding: 3px;\n"
"color: rgb(223, 223, 223);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.volume2Label_layout.addWidget(self.label_14)
        self.vol2Widget_layout.addLayout(self.volume2Label_layout)
        self.vol2ControlsWidget = QtGui.QWidget(data)
        self.vol2ControlsWidget.setMinimumSize(QtCore.QSize(300, 80))
        self.vol2ControlsWidget.setObjectName(_fromUtf8("vol2ControlsWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.vol2ControlsWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.layoutVolume2 = QtGui.QVBoxLayout()
        self.layoutVolume2.setObjectName(_fromUtf8("layoutVolume2"))
        self.comboBoxVolume2 = QtGui.QComboBox(self.vol2ControlsWidget)
        self.comboBoxVolume2.setObjectName(_fromUtf8("comboBoxVolume2"))
        self.layoutVolume2.addWidget(self.comboBoxVolume2)
        self.horizontalLayoutVol2Levels = QtGui.QHBoxLayout()
        self.horizontalLayoutVol2Levels.setObjectName(_fromUtf8("horizontalLayoutVol2Levels"))
        self.comboBoxVolumeLut2 = QtGui.QComboBox(self.vol2ControlsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxVolumeLut2.sizePolicy().hasHeightForWidth())
        self.comboBoxVolumeLut2.setSizePolicy(sizePolicy)
        self.comboBoxVolumeLut2.setObjectName(_fromUtf8("comboBoxVolumeLut2"))
        self.horizontalLayoutVol2Levels.addWidget(self.comboBoxVolumeLut2)
        self.layoutVolume2.addLayout(self.horizontalLayoutVol2Levels)
        self.verticalLayout_3.addLayout(self.layoutVolume2)
        self.vol2Widget_layout.addWidget(self.vol2ControlsWidget)
        self.verticalLayout.addLayout(self.vol2Widget_layout)
        self.line_2 = QtGui.QFrame(data)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxShowDataControls = QtGui.QCheckBox(data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowDataControls.sizePolicy().hasHeightForWidth())
        self.checkBoxShowDataControls.setSizePolicy(sizePolicy)
        self.checkBoxShowDataControls.setText(_fromUtf8(""))
        self.checkBoxShowDataControls.setObjectName(_fromUtf8("checkBoxShowDataControls"))
        self.horizontalLayout_3.addWidget(self.checkBoxShowDataControls)
        self.labelData = QtGui.QLabel(data)
        self.labelData.setStyleSheet(_fromUtf8("background-color:rgb(102, 95, 95);\n"
"padding: 3px;\n"
"color: rgb(223, 223, 223);"))
        self.labelData.setObjectName(_fromUtf8("labelData"))
        self.horizontalLayout_3.addWidget(self.labelData)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.dataWidget = QtGui.QWidget(data)
        self.dataWidget.setMinimumSize(QtCore.QSize(0, 170))
        self.dataWidget.setObjectName(_fromUtf8("dataWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dataWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.comboBoxData = QtGui.QComboBox(self.dataWidget)
        self.comboBoxData.setObjectName(_fromUtf8("comboBoxData"))
        self.verticalLayout_8.addWidget(self.comboBoxData)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.comboBoxLutHeatmap = QtGui.QComboBox(self.dataWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLutHeatmap.sizePolicy().hasHeightForWidth())
        self.comboBoxLutHeatmap.setSizePolicy(sizePolicy)
        self.comboBoxLutHeatmap.setObjectName(_fromUtf8("comboBoxLutHeatmap"))
        self.horizontalLayout_11.addWidget(self.comboBoxLutHeatmap)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.doubleSpinBoxNegThresh = QtGui.QDoubleSpinBox(self.dataWidget)
        self.doubleSpinBoxNegThresh.setObjectName(_fromUtf8("doubleSpinBoxNegThresh"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxNegThresh)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButtonRecalcConnectComponents = QtGui.QPushButton(self.dataWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRecalcConnectComponents.sizePolicy().hasHeightForWidth())
        self.pushButtonRecalcConnectComponents.setSizePolicy(sizePolicy)
        self.pushButtonRecalcConnectComponents.setObjectName(_fromUtf8("pushButtonRecalcConnectComponents"))
        self.horizontalLayout_6.addWidget(self.pushButtonRecalcConnectComponents)
        self.doubleSpinBoxPosThresh = QtGui.QDoubleSpinBox(self.dataWidget)
        self.doubleSpinBoxPosThresh.setObjectName(_fromUtf8("doubleSpinBoxPosThresh"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxPosThresh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.labelFdrThresholds = QtGui.QLabel(self.dataWidget)
        self.labelFdrThresholds.setObjectName(_fromUtf8("labelFdrThresholds"))
        self.verticalLayout_4.addWidget(self.labelFdrThresholds)
        self.gridLayoutFdrButtons = QtGui.QGridLayout()
        self.gridLayoutFdrButtons.setObjectName(_fromUtf8("gridLayoutFdrButtons"))
        self.verticalLayout_4.addLayout(self.gridLayoutFdrButtons)
        self.horizontalLayoutDataSliders = QtGui.QHBoxLayout()
        self.horizontalLayoutDataSliders.setObjectName(_fromUtf8("horizontalLayoutDataSliders"))
        self.verticalLayout_4.addLayout(self.horizontalLayoutDataSliders)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayoutConnectedComponents = QtGui.QHBoxLayout()
        self.verticalLayoutConnectedComponents.setObjectName(_fromUtf8("verticalLayoutConnectedComponents"))
        self.verticalLayout_4.addLayout(self.verticalLayoutConnectedComponents)
        self.labelFdrThresholds.raise_()
        self.verticalLayout.addWidget(self.dataWidget)
        self.line_4 = QtGui.QFrame(data)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.verticalLayoutVectors = QtGui.QVBoxLayout()
        self.verticalLayoutVectors.setObjectName(_fromUtf8("verticalLayoutVectors"))
        self.horizontalLayoutVectorHeader = QtGui.QHBoxLayout()
        self.horizontalLayoutVectorHeader.setObjectName(_fromUtf8("horizontalLayoutVectorHeader"))
        self.checkBoxShowVectorControls = QtGui.QCheckBox(data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowVectorControls.sizePolicy().hasHeightForWidth())
        self.checkBoxShowVectorControls.setSizePolicy(sizePolicy)
        self.checkBoxShowVectorControls.setText(_fromUtf8(""))
        self.checkBoxShowVectorControls.setObjectName(_fromUtf8("checkBoxShowVectorControls"))
        self.horizontalLayoutVectorHeader.addWidget(self.checkBoxShowVectorControls)
        self.label_9 = QtGui.QLabel(data)
        self.label_9.setStyleSheet(_fromUtf8("background-color:rgb(102, 95, 95);\n"
"padding: 3px;\n"
"color: rgb(223, 223, 223);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayoutVectorHeader.addWidget(self.label_9)
        self.verticalLayoutVectors.addLayout(self.horizontalLayoutVectorHeader)
        self.vectorWidget = QtGui.QWidget(data)
        self.vectorWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.vectorWidget.setObjectName(_fromUtf8("vectorWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.vectorWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBoxVectors = QtGui.QComboBox(self.vectorWidget)
        self.comboBoxVectors.setObjectName(_fromUtf8("comboBoxVectors"))
        self.verticalLayout_2.addWidget(self.comboBoxVectors)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(self.vectorWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.spinBoxVectorSubsampling = QtGui.QSpinBox(self.vectorWidget)
        self.spinBoxVectorSubsampling.setObjectName(_fromUtf8("spinBoxVectorSubsampling"))
        self.horizontalLayout_7.addWidget(self.spinBoxVectorSubsampling)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_11 = QtGui.QLabel(self.vectorWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.spinBoxVectorScale = QtGui.QSpinBox(self.vectorWidget)
        self.spinBoxVectorScale.setObjectName(_fromUtf8("spinBoxVectorScale"))
        self.horizontalLayout_7.addWidget(self.spinBoxVectorScale)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_12 = QtGui.QLabel(self.vectorWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.pushButtonVectorColor = QtGui.QPushButton(self.vectorWidget)
        self.pushButtonVectorColor.setText(_fromUtf8(""))
        self.pushButtonVectorColor.setObjectName(_fromUtf8("pushButtonVectorColor"))
        self.horizontalLayout_7.addWidget(self.pushButtonVectorColor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.pushButtonVectorMagnitudeFilter = QtGui.QPushButton(self.vectorWidget)
        self.pushButtonVectorMagnitudeFilter.setObjectName(_fromUtf8("pushButtonVectorMagnitudeFilter"))
        self.verticalLayout_2.addWidget(self.pushButtonVectorMagnitudeFilter)
        self.horizontalLayoutMagnitudeSlider = QtGui.QHBoxLayout()
        self.horizontalLayoutMagnitudeSlider.setObjectName(_fromUtf8("horizontalLayoutMagnitudeSlider"))
        self.verticalLayout_2.addLayout(self.horizontalLayoutMagnitudeSlider)
        self.verticalLayoutVectors.addWidget(self.vectorWidget)
        self.verticalLayout.addLayout(self.verticalLayoutVectors)
        self.line_3 = QtGui.QFrame(data)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayoutScalebar = QtGui.QGridLayout()
        self.gridLayoutScalebar.setObjectName(_fromUtf8("gridLayoutScalebar"))
        self.doubleSpinBoxVoxelSize = QtGui.QDoubleSpinBox(data)
        self.doubleSpinBoxVoxelSize.setObjectName(_fromUtf8("doubleSpinBoxVoxelSize"))
        self.gridLayoutScalebar.addWidget(self.doubleSpinBoxVoxelSize, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(data)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayoutScalebar.addWidget(self.label_15, 0, 0, 1, 1)
        self.doubleSpinBoxScaleBarLength = QtGui.QDoubleSpinBox(data)
        self.doubleSpinBoxScaleBarLength.setObjectName(_fromUtf8("doubleSpinBoxScaleBarLength"))
        self.gridLayoutScalebar.addWidget(self.doubleSpinBoxScaleBarLength, 0, 4, 1, 1)
        self.label_16 = QtGui.QLabel(data)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayoutScalebar.addWidget(self.label_16, 0, 3, 1, 1)
        self.checkBoxScaleBarLabel = QtGui.QCheckBox(data)
        self.checkBoxScaleBarLabel.setObjectName(_fromUtf8("checkBoxScaleBarLabel"))
        self.gridLayoutScalebar.addWidget(self.checkBoxScaleBarLabel, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutScalebar)
        self.line_9 = QtGui.QFrame(data)
        self.line_9.setLineWidth(4)
        self.line_9.setMidLineWidth(2)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout.addWidget(self.line_9)
        self.verticalLayoutColorScale = QtGui.QVBoxLayout()
        self.verticalLayoutColorScale.setObjectName(_fromUtf8("verticalLayoutColorScale"))
        self.verticalLayout.addLayout(self.verticalLayoutColorScale)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(data)
        QtCore.QMetaObject.connectSlotsByName(data)

    def retranslateUi(self, data):
        data.setWindowTitle(_translate("data", "Form", None))
        self.label_13.setText(_translate("data", "Viewport visiblity", None))
        self.label.setText(_translate("data", "Edit viewport", None))
        self.checkBoxInterpolate.setText(_translate("data", "Interpolate volumes", None))
        self.checkBoxLinkViews.setText(_translate("data", "Link views", None))
        self.checkBox6Views.setText(_translate("data", "Two row view", None))
        self.label_2.setText(_translate("data", "Orientation", None))
        self.comboBoxOrientation.setItemText(0, _translate("data", "sagittal", None))
        self.comboBoxOrientation.setItemText(1, _translate("data", "coronal", None))
        self.comboBoxOrientation.setItemText(2, _translate("data", "axial", None))
        self.comboBoxOrientation.setItemText(3, _translate("data", "Isosurface - Not implemented", None))
        self.checkBoxFlipXY.setText(_translate("data", "flip x/y", None))
        self.pushButtonScaleBarColor.setText(_translate("data", "scale bar color", None))
        self.labelVolume.setText(_translate("data", "Volume 1", None))
        self.label_14.setText(_translate("data", "Volume 2", None))
        self.labelData.setText(_translate("data", "Heatmap Data", None))
        self.pushButtonRecalcConnectComponents.setText(_translate("data", "Find blobs", None))
        self.labelFdrThresholds.setText(_translate("data", "FDR thresholds", None))
        self.label_9.setText(_translate("data", "Vectors", None))
        self.label_10.setText(_translate("data", "Subsample", None))
        self.label_11.setText(_translate("data", "Scale", None))
        self.label_12.setText(_translate("data", "Arrow colour", None))
        self.pushButtonVectorMagnitudeFilter.setText(_translate("data", "filter magnitude", None))
        self.label_15.setText(_translate("data", "Voxel size", None))
        self.label_16.setText(_translate("data", "Scale bar length", None))
        self.checkBoxScaleBarLabel.setText(_translate("data", "scale label", None))

import resources_rc
