# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_importer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(854, 373)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 130))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonChooseFile = QtWidgets.QPushButton(Dialog)
        self.pushButtonChooseFile.setObjectName("pushButtonChooseFile")
        self.horizontalLayout.addWidget(self.pushButtonChooseFile)
        self.pushButtonChoseDir = QtWidgets.QPushButton(Dialog)
        self.pushButtonChoseDir.setObjectName("pushButtonChoseDir")
        self.horizontalLayout.addWidget(self.pushButtonChoseDir)
        self.checkBoxMemoryMap = QtWidgets.QCheckBox(Dialog)
        self.checkBoxMemoryMap.setChecked(False)
        self.checkBoxMemoryMap.setObjectName("checkBoxMemoryMap")
        self.horizontalLayout.addWidget(self.checkBoxMemoryMap)
        self.checkBoxAllSameType = QtWidgets.QCheckBox(Dialog)
        self.checkBoxAllSameType.setObjectName("checkBoxAllSameType")
        self.horizontalLayout.addWidget(self.checkBoxAllSameType)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutVirtualStack = QtWidgets.QVBoxLayout()
        self.verticalLayoutVirtualStack.setObjectName("verticalLayoutVirtualStack")
        self.virtualStackWidget = QtWidgets.QWidget(Dialog)
        self.virtualStackWidget.setMinimumSize(QtCore.QSize(0, 130))
        self.virtualStackWidget.setObjectName("virtualStackWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.virtualStackWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.virtualStackWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditFileNameContains = QtWidgets.QLineEdit(self.virtualStackWidget)
        self.lineEditFileNameContains.setObjectName("lineEditFileNameContains")
        self.gridLayout.addWidget(self.lineEditFileNameContains, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.virtualStackWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditFileNameDoesNotContain = QtWidgets.QLineEdit(self.virtualStackWidget)
        self.lineEditFileNameDoesNotContain.setObjectName("lineEditFileNameDoesNotContain")
        self.gridLayout.addWidget(self.lineEditFileNameDoesNotContain, 1, 1, 1, 1)
        self.pushButtonFilter = QtWidgets.QPushButton(self.virtualStackWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilter.sizePolicy().hasHeightForWidth())
        self.pushButtonFilter.setSizePolicy(sizePolicy)
        self.pushButtonFilter.setObjectName("pushButtonFilter")
        self.gridLayout.addWidget(self.pushButtonFilter, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.virtualStackWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.labelNumberOfFiles = QtWidgets.QLabel(self.virtualStackWidget)
        self.labelNumberOfFiles.setText("")
        self.labelNumberOfFiles.setObjectName("labelNumberOfFiles")
        self.horizontalLayout_3.addWidget(self.labelNumberOfFiles)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.verticalLayoutVirtualStack.addWidget(self.virtualStackWidget)
        self.verticalLayout.addLayout(self.verticalLayoutVirtualStack)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setLineWidth(2)
        self.table.setMidLineWidth(1)
        self.table.setColumnCount(3)
        self.table.setObjectName("table")
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonUp = QtWidgets.QPushButton(Dialog)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.horizontalLayout_2.addWidget(self.pushButtonUp)
        self.pushButtonDown = QtWidgets.QPushButton(Dialog)
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.horizontalLayout_2.addWidget(self.pushButtonDown)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonOK = QtWidgets.QPushButton(Dialog)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_2.addWidget(self.pushButtonOK)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonChooseFile.setText(_translate("Dialog", "Choose files"))
        self.pushButtonChoseDir.setText(_translate("Dialog", "Load stack of 2D slices"))
        self.checkBoxMemoryMap.setText(_translate("Dialog", "memory map volumes"))
        self.checkBoxAllSameType.setText(_translate("Dialog", "All same type?"))
        self.label.setText(_translate("Dialog", "Filename contains (eg:.   .tiff)"))
        self.label_2.setText(_translate("Dialog", "Filename does not contain (eg: spr.tif, rec.tif)"))
        self.pushButtonFilter.setText(_translate("Dialog", "Filter"))
        self.label_4.setText(_translate("Dialog", "Number of files:"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Data"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Type"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Load?"))
        self.pushButtonUp.setText(_translate("Dialog", "up"))
        self.pushButtonDown.setText(_translate("Dialog", "down"))
        self.pushButtonOK.setText(_translate("Dialog", "OK"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))

