# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_importer.ui'
#
# Created: Tue Sep  6 14:23:55 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(854, 373)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 130))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonChooseFile = QtGui.QPushButton(Dialog)
        self.pushButtonChooseFile.setObjectName(_fromUtf8("pushButtonChooseFile"))
        self.horizontalLayout.addWidget(self.pushButtonChooseFile)
        self.pushButtonChoseDir = QtGui.QPushButton(Dialog)
        self.pushButtonChoseDir.setObjectName(_fromUtf8("pushButtonChoseDir"))
        self.horizontalLayout.addWidget(self.pushButtonChoseDir)
        self.checkBoxMemoryMap = QtGui.QCheckBox(Dialog)
        self.checkBoxMemoryMap.setChecked(False)
        self.checkBoxMemoryMap.setObjectName(_fromUtf8("checkBoxMemoryMap"))
        self.horizontalLayout.addWidget(self.checkBoxMemoryMap)
        self.checkBoxAllSameType = QtGui.QCheckBox(Dialog)
        self.checkBoxAllSameType.setObjectName(_fromUtf8("checkBoxAllSameType"))
        self.horizontalLayout.addWidget(self.checkBoxAllSameType)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutVirtualStack = QtGui.QVBoxLayout()
        self.verticalLayoutVirtualStack.setObjectName(_fromUtf8("verticalLayoutVirtualStack"))
        self.virtualStackWidget = QtGui.QWidget(Dialog)
        self.virtualStackWidget.setMinimumSize(QtCore.QSize(0, 130))
        self.virtualStackWidget.setObjectName(_fromUtf8("virtualStackWidget"))
        self.gridLayout = QtGui.QGridLayout(self.virtualStackWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.virtualStackWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditFileNameContains = QtGui.QLineEdit(self.virtualStackWidget)
        self.lineEditFileNameContains.setObjectName(_fromUtf8("lineEditFileNameContains"))
        self.gridLayout.addWidget(self.lineEditFileNameContains, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.virtualStackWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditFileNameDoesNotContain = QtGui.QLineEdit(self.virtualStackWidget)
        self.lineEditFileNameDoesNotContain.setObjectName(_fromUtf8("lineEditFileNameDoesNotContain"))
        self.gridLayout.addWidget(self.lineEditFileNameDoesNotContain, 1, 1, 1, 1)
        self.pushButtonFilter = QtGui.QPushButton(self.virtualStackWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilter.sizePolicy().hasHeightForWidth())
        self.pushButtonFilter.setSizePolicy(sizePolicy)
        self.pushButtonFilter.setObjectName(_fromUtf8("pushButtonFilter"))
        self.gridLayout.addWidget(self.pushButtonFilter, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.virtualStackWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.labelNumberOfFiles = QtGui.QLabel(self.virtualStackWidget)
        self.labelNumberOfFiles.setText(_fromUtf8(""))
        self.labelNumberOfFiles.setObjectName(_fromUtf8("labelNumberOfFiles"))
        self.horizontalLayout_3.addWidget(self.labelNumberOfFiles)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.verticalLayoutVirtualStack.addWidget(self.virtualStackWidget)
        self.verticalLayout.addLayout(self.verticalLayoutVirtualStack)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.table = QtGui.QTableWidget(Dialog)
        self.table.setLineWidth(2)
        self.table.setMidLineWidth(1)
        self.table.setColumnCount(3)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonUp = QtGui.QPushButton(Dialog)
        self.pushButtonUp.setObjectName(_fromUtf8("pushButtonUp"))
        self.horizontalLayout_2.addWidget(self.pushButtonUp)
        self.pushButtonDown = QtGui.QPushButton(Dialog)
        self.pushButtonDown.setObjectName(_fromUtf8("pushButtonDown"))
        self.horizontalLayout_2.addWidget(self.pushButtonDown)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonOK = QtGui.QPushButton(Dialog)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.horizontalLayout_2.addWidget(self.pushButtonOK)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButtonChooseFile.setText(_translate("Dialog", "Choose files", None))
        self.pushButtonChoseDir.setText(_translate("Dialog", "Load stack of 2D slices", None))
        self.checkBoxMemoryMap.setText(_translate("Dialog", "memory map volumes", None))
        self.checkBoxAllSameType.setText(_translate("Dialog", "All same type?", None))
        self.label.setText(_translate("Dialog", "Filename contains (eg:.   .tiff)", None))
        self.label_2.setText(_translate("Dialog", "Filename does not contain (eg: spr.tif, rec.tif)", None))
        self.pushButtonFilter.setText(_translate("Dialog", "Filter", None))
        self.label_4.setText(_translate("Dialog", "Number of files:", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Data", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Type", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Load?", None))
        self.pushButtonUp.setText(_translate("Dialog", "up", None))
        self.pushButtonDown.setText(_translate("Dialog", "down", None))
        self.pushButtonOK.setText(_translate("Dialog", "OK", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel", None))

